[NAOqi Address]
NAOqiIP=127.0.0.1
NAOqiPort=9559

[GameController Address]
gameControllerIP=192.168.42.128
readingPort=3838
writingPort=3939

[TeamCommunication Address]
broadcast=192.168.42.128
multicast=192.168.42.128
teamPort=10031

[GameController Data]
unbeatablesNumber=31
playerNumber=1

[System Settings]
; 1:NAOQI, 2:V4L2
camera=1
; Cascade file name
cascade=cascade-2024-10.xml