from enum import Enum

class CompetitionPhase(Enum):
    COMPETITION_PHASE_ROUNDROBIN = 0
    COMPETITION_PHASE_PLAYOFF = 1

class CompetitionType(Enum):
    COMPETITION_TYPE_NORMAL = 0
    COMPETITION_TYPE_SHARED_AUTONOMY = 1

class GamePhase(Enum):
    GAME_PHASE_NORMAL = 0
    GAME_PHASE_PENALTYSHOOT = 1
    GAME_PHASE_OVERTIME = 2
    GAME_PHASE_TIMEOUT = 3

class State(Enum):
    STATE_INITIAL = 0
    STATE_READY = 1
    STATE_SET = 2
    STATE_PLAYING = 3
    STATE_FINISHED = 4
    STATE_STANDBY = 5

class SetPlay(Enum):
    SET_PLAY_NONE = 0
    SET_PLAY_GOAL_KICK = 1
    SET_PLAY_PUSHING_FREE_KICK = 2
    SET_PLAY_CORNER_KICK = 3
    SET_PLAY_KICK_IN = 4
    SET_PLAY_PENALTY_KICK = 5

class SetPlay(Enum):
    SET_PLAY_NONE = 0
    SET_PLAY_GOAL_KICK = 1
    SET_PLAY_PUSHING_FREE_KICK = 2
    SET_PLAY_CORNER_KICK = 3
    SET_PLAY_KICK_IN = 4
    SET_PLAY_PENALTY_KICK = 5
